### ISSUE TITLE
Document how to set the "Max Message Length" of a message (default set at 2048)

### ISSUE THREAD

**Issue by MarkAPhillips** [merchantwarehouse/syslog4net#4] opened 2015-06-29 09:34 UTC
Please could you include this in your documentation if possible.
I tried to set it as follows - but it still seems to be truncating still

```
 <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
      <file value="logs"xxxxlogs />
      <appendToFile value="true" />
      <rollingStyle value="Date" />
      <staticLogFileName value="false" />
      <maxSizeRollBackups value="10" />
      <maximumFileSize value="1GB" />
      <layout type="syslog4net.Layout.SyslogLayout, syslog4net">
        <structuredDataPrefix value="xxxx" />
        <maxMessageLength value="10000"/>
      </layout>
    </appender>
```

Thanks

**Comment by mesteves-mw** [comment] 2015-06-29 10:52
The Max Message Length is hard-coded in the SyslogLayout to 2048 and it appears to be by design.
https://github.com/merchantwarehouse/syslog4net/blob/master/src/main/dot-net/syslog4net/Layout/SyslogLayout.cs#L20

For testing purposes only I suggest you use another Layout. Something like this would not trim the message:
```xml
<layout type="log4net.Layout.PatternLayout">
   <conversionPattern value="%date [%thread] %-5level %logger [%property{NDC}] - %message%newline" />
</layout>

**Comment by MarkAPhillips** [comment] 2015-06-29 10:57
Hi if you check this commit https://github.com/merchantwarehouse/syslog4net/commit/01f7065687a9e355a9a5c00dddcc5d8e1ebb9ec1

it seems this was made configurable - so therefore I assume can be amended. Can this be confirmed. Thanks

**Comment by mesteves-mw** [comment] 2015-06-29 11:58
You are right, it looks like the Layout class is overriding the hard-coded value.
Although the latest release version 1.0.9 seems to be older than the commit
https://github.com/merchantwarehouse/syslog4net/releases

If you compiled syslog4net locally then try this instead:
```xml
<layout type="syslog4net.Layout.SyslogLayout, syslog4net">
  <structuredDataPrefix value="MW@55555"/>
  <param name="MaxMessageLength" value="10000" />
</layout>

**Comment by MarkAPhillips** [comment] 2015-06-29 12:18
Thanks - appreciate it.  I would prefer a new release created if possible (as use nuget to manage all my dependencies) with this enhancement included but if the author is no longer maintaining this project - will pull a copy down locally as there are some modifications I would like to make anyway to code base - I will see what happens over the next week. Thanks again.

**Comment by dlachowicz-mw** [comment] 2015-10-23 12:07
Code is merged. New release is being worked on.

**Closed by dlachowicz-mw** 2015-10-23 12:07 UTC
